# Generated by Django 3.2.13 on 2025-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
